---
name: lint
on: [push, pull_request]  # yamllint disable-line rule:truthy

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: "git config --global core.autocrlf input"
      - uses: actions/checkout@v4
        with:
          path: ${{ github.repository }}
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/meta
          path: ${{ github.repository_owner }}/meta
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ${{ github.repository }}
          args: |
            --config="${{ inputs.golangci_path || format('{0}/{1}/meta/golangci.yml', github.workspace, github.repository_owner) }}" --timeout=5m
